[package]
name = "webinterop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.43", features = ["full"] }
quote = { version = "1.0.33", features = [] }
proc-macro2 = "1.0.69"
serde = { version = "1.0.193", features = ["derive"] }
lazy_static = "1.4.0"


[lib]
proc-macro = true
