[package]
name = "gosub_vello"
version = "0.1.0"
edition = "2021"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_render_backend = { path = "../gosub_render_backend" }
gosub_typeface = { path = "../gosub_typeface" }
vello = "0.1.0"
image = "0.25.1"
smallvec = "1.13.2"