[package]
name = "gosub_useragent"
version = "0.1.0"
edition = "2021"

[dependencies]
gosub_shared = { path = "../gosub_shared" }
gosub_render_backend = { path = "../gosub_render_backend" }
gosub_renderer = { path = "../gosub_renderer" }
winit = "0.30.0"
slotmap = "1.0.7"
log = "0.4.21"
anyhow = "1.0.82"
url = "2.5.0"
